// Bộ 120 câu trắc nghiệm Đại số tuyến tính (nền tảng)
// [id, chương, câu hỏi, [đáp án], chỉ số đáp án đúng, giải thích]
export const CHAPTERS = [
  { id: 1, name: "Scalar, Variable và Constant", range: "Câu 1–16" },
  { id: 2, name: "Vector", range: "Câu 17–34" },
  { id: 3, name: "Matrix", range: "Câu 35–50" },
  { id: 4, name: "Tensor", range: "Câu 51–60" },
  { id: 5, name: "Các phép toán trên vector và ma trận", range: "Câu 61–82" },
  { id: 6, name: "Bản chất ma trận: Hệ phương trình tuyến tính", range: "Câu 83–102" },
  { id: 7, name: "Phép nhân ma trận với vector", range: "Câu 103–120" },
];

const TF = ["Đúng", "Sai"];
const raw = [
[1,1,"Scalar là gì?",["Một danh sách có thứ tự gồm nhiều con số","Một giá trị đơn — một con số duy nhất","Một bảng số hai chiều","Một mảng số nhiều chiều"],1,"Scalar là một giá trị đơn, một con số duy nhất. (Mục 1.1 — Scalar)"],
[2,1,"Theo cách phân loại theo số chiều, scalar là đối tượng:",["Một chiều","Hai chiều","Không chiều (0 chiều)","Ba chiều"],2,"Scalar không chiều: một con số đứng một mình, không cần trục nào để sắp xếp. (Mục 1.1)"],
[3,1,"Ký hiệu x ∈ ℝ có nghĩa là gì?",["x là một vector thuộc không gian thực","x là một ma trận thực","x là một số thực (một scalar)","x là một tập hợp các số thực"],2,"x ∈ ℝ đọc là “x thuộc tập số thực”, tức x là một scalar. (Mục 1.1)"],
[4,1,"Variable (biến số) được định nghĩa là:",["Một giá trị luôn cố định trong mọi bài toán","Một giá trị chưa biết, hoặc có thể thay đổi trong bài toán đang xét","Một giá trị luôn bằng 0","Một con số nguyên dương"],1,"Variable là giá trị chưa biết hoặc có thể thay đổi trong bài toán đang xét. (Mục 1.2)"],
[5,1,"Constant (hằng số) được định nghĩa là:",["Một giá trị đã biết trước, hoặc được giữ cố định trong bài toán hiện tại","Một giá trị luôn thay đổi","Một vector có nhiều thành phần","Một giá trị chưa xác định"],0,"Constant là scalar có giá trị đã biết trước hoặc cố định trong ngữ cảnh hiện tại. (Mục 1.3)"],
[6,1,"Trong phương trình 2x + 3 = 7, đại lượng nào đóng vai trò variable?",["Số 3","Số 7","x","Số 2"],2,"x là ẩn số chưa biết → variable. (Mục 1.2)"],
[7,1,"Trong phương trình 2x + 3 = 7, các số 3 và 7 đóng vai trò gì?",["Variable","Constant","Vector","Matrix"],1,"3 và 7 là những giá trị cố định đã biết → constant. (Mục 1.3)"],
[8,1,"Một con số là variable hay constant phụ thuộc vào điều gì?",["Con số đó lớn hay nhỏ","Con số đó âm hay dương","Vai trò của nó trong bài toán đang xét (ngữ cảnh)","Con số đó nguyên hay thực"],2,"Vai trò variable/constant không cố hữu, mà phụ thuộc ngữ cảnh bài toán. (Mục 1.3)"],
[9,1,"Trong công thức price = w × area + b, ở giai đoạn huấn luyện (đi tìm công thức), w và b đóng vai trò gì?",["Constant, vì chúng cố định","Variable, vì chúng là ẩn số cần tìm","Vector kết quả","Ma trận hệ số"],1,"Ở giai đoạn huấn luyện, w và b là ẩn số cần tìm → variable. (Mục 1.3)"],
[10,1,"Sau khi đã tìm được w = 1400 và b = 1200, thì w và b trong công thức dự đoán đóng vai trò gì?",["Variable","Constant","Vector","Random variable"],1,"Sau khi tìm được giá trị, w và b “đóng băng” thành con số cố định → constant. (Mục 1.3)"],
[11,1,"Khi công thức price = 1400 × area + 1200 đã cố định, đại lượng nào đóng vai trò variable?",["area","Số 1400","Số 1200","price luôn cố định"],0,"area là đầu vào thay đổi tùy từng căn nhà → variable. (Mục 1.3)"],
[12,1,"(Đúng/Sai) Một đại lượng đã là variable trong một bài toán thì mãi mãi là variable trong mọi bài toán khác.",TF,1,"Sai — một đại lượng có thể là variable ở bài toán này và constant ở bài toán khác. (Mục 1.3)"],
[13,1,"Scalar thường được ký hiệu bằng:",["Chữ cái in hoa in đậm","Chữ cái viết thường (không in đậm)","Chữ cái viết thường in đậm","Ký hiệu mũi tên"],1,"Scalar ký hiệu bằng chữ cái viết thường, không in đậm. (Mục 1.1, 2.1)"],
[14,1,"(Đúng/Sai) Cùng hai ký hiệu w và b có thể là variable ở giai đoạn huấn luyện và là constant ở giai đoạn dự đoán.",TF,0,"Đúng — đây chính là ý nghĩa của “vai trò phụ thuộc ngữ cảnh”. (Mục 1.3)"],
[15,1,"Đâu là ví dụ đúng về một scalar?",["[1 2 3]","Số 5","Một bảng gồm 6 con số","Một ảnh RGB"],1,"Số 5 là một giá trị đơn → scalar. Các lựa chọn khác là vector/bảng/ảnh. (Mục 1.1)"],
[16,1,"Điều nào mô tả đúng mối quan hệ giữa scalar, variable và constant?",["Variable và constant là hai loại đối tượng hoàn toàn khác scalar","Variable và constant đều là scalar, chỉ khác nhau ở vai trò trong bài toán","Constant là một loại vector đặc biệt","Scalar là trường hợp đặc biệt của variable"],1,"Variable và constant đều là scalar, chỉ khác vai trò. (Mục 1.1–1.3)"],
[17,2,"Vector là gì?",["Một con số duy nhất","Một danh sách có thứ tự gồm nhiều scalar","Một bảng số hai chiều","Một phép biến đổi"],1,"Vector là danh sách có thứ tự gồm nhiều scalar. (Mục 2.1)"],
[18,2,"Theo cách phân loại theo số chiều, vector là đối tượng:",["Không chiều","Một chiều","Hai chiều","Ba chiều"],1,"Vector là đối tượng một chiều: các số xếp thành dãy dọc theo một trục. (Mục 2.1)"],
[19,2,"Vector thường được ký hiệu bằng:",["Chữ cái viết thường in đậm","Chữ cái in hoa","Chữ số","Chữ cái viết thường không in đậm"],0,"Vector ký hiệu bằng chữ cái viết thường in đậm. (Mục 2.1)"],
[20,2,"Ký hiệu x ∈ ℝᵐ có nghĩa là gì?",["x là một số thực","x là một vector gồm m số thực","x là một ma trận m × m","x là một tensor bậc m"],1,"x ∈ ℝᵐ nghĩa là vector gồm m số thực. (Mục 2.1)"],
[21,2,"Sự khác nhau cốt lõi giữa ℝ và ℝᵐ là gì?",["ℝ là số phức, ℝᵐ là số thực","ℝ là tập các số thực (một số); ℝᵐ là tập các vector gồm m số thực","Không có khác biệt gì","ℝ chỉ chứa số nguyên"],1,"ℝ là tập số thực (một số = scalar); ℝᵐ là tập vector gồm m số thực. (Mục 2.1)"],
[22,2,"Vector v = [5 2 9]ᵀ thuộc không gian nào?",["ℝ","ℝ²","ℝ³","ℝ⁹"],2,"Vector có 3 thành phần nên thuộc ℝ³. (Mục 2.1)"],
[23,2,"Số mũ m trong ký hiệu ℝᵐ cho biết điều gì?",["Giá trị lớn nhất của vector","Số thành phần của vector","Số chiều của không gian ảnh","Tổng các phần tử của vector"],1,"Số mũ m cho biết vector có bao nhiêu thành phần. (Mục 2.1)"],
[24,2,"Nhiều giá trị scalar hợp lại theo chiều dọc tạo thành:",["Vector hàng","Vector cột","Ma trận","Scalar"],1,"Nhiều scalar hợp lại theo chiều dọc tạo thành vector cột. (Mục 2.1)"],
[25,2,"Vector hàng thu được từ vector cột bằng phép toán nào?",["Phép cộng","Phép nhân","Phép chuyển vị (transpose)","Phép broadcasting"],2,"Vector hàng thu được bằng phép chuyển vị. (Mục 2.2)"],
[26,2,"Ký hiệu ⊤ trong xᵀ đại diện cho:",["Phép nhân","Phép chuyển vị (transpose)","Phép nghịch đảo","Phép lấy độ dài"],1,"⊤ là ký hiệu chuyển vị. (Mục 2.2)"],
[27,2,"Phép chuyển vị làm thay đổi điều gì?",["Giá trị của các thành phần","Cách sắp xếp (cột ↔ hàng), không đổi giá trị","Số lượng phần tử","Dấu của các thành phần"],1,"Chuyển vị chỉ đổi cách sắp xếp, không đổi giá trị. (Mục 2.2)"],
[28,2,"Theo quy ước phổ biến, nếu không nói gì thêm thì một vector được hiểu mặc định là:",["Vector hàng","Vector cột","Ma trận vuông","Scalar"],1,"Mặc định vector được hiểu là vector cột. (Mục 2.3)"],
[29,2,"(Đúng/Sai) Quy ước “vector mặc định là vector cột” là một định luật toán học bắt buộc trong mọi tài liệu.",TF,1,"Sai — đây chỉ là quy ước phổ biến, không phải định luật bắt buộc. (Mục 2.3)"],
[30,2,"Theo “thần chú” trong bối cảnh dữ liệu, vector cột thường đại diện cho:",["Một sample","Một feature","Một bảng dữ liệu","Một tensor"],1,"Vector cột thường đại diện cho một feature. (Mục 2.3)"],
[31,2,"Theo “thần chú” trong bối cảnh dữ liệu, vector hàng thường đại diện cho:",["Một feature","Một sample gồm nhiều feature","Một scalar","Một phép biến đổi"],1,"Vector hàng thường đại diện cho một sample gồm nhiều feature. (Mục 2.3)"],
[32,2,"Một số tài liệu dùng ký hiệu nào khác để chỉ vector chuyển vị (ngoài xᵀ)?",["x*","x′ (dấu phẩy trên)","x⁻¹","|x|"],1,"Một số tài liệu dùng x′, nhưng xᵀ phổ biến và rõ hơn. (Mục 2.2)"],
[33,2,"Trong vector cột x = [x₁ x₂ … xₘ]ᵀ, mỗi xᵢ là:",["Một vector","Một ma trận","Một scalar (thành phần đơn lẻ)","Một tensor"],2,"Mỗi xᵢ viết thường là một scalar — thành phần đơn lẻ của vector. (Mục 2.1)"],
[34,2,"Vì sao x (in đậm) và x (không đậm) không nên hiểu là cùng một loại đối tượng?",["Vì chúng có màu khác nhau","Vì x in đậm là vector (nhiều số), còn x không đậm là scalar (một số)","Vì x luôn lớn hơn x","Vì chúng thuộc hai môn học khác nhau"],1,"x in đậm là vector; x không đậm là scalar. (Mục 2.1)"],
[35,3,"Matrix (ma trận) là gì?",["Một con số duy nhất","Một danh sách một chiều các số","Một mảng số hai chiều, sắp xếp thành hàng và cột","Một phép biến đổi tuyến tính"],2,"Matrix là mảng số hai chiều, sắp xếp thành hàng và cột. (Mục 3.1)"],
[36,3,"Theo cách phân loại theo số chiều, matrix là đối tượng:",["Không chiều","Một chiều","Hai chiều","Bốn chiều"],2,"Matrix là đối tượng hai chiều. (Mục 3.1)"],
[37,3,"Một cách nhìn hữu ích: ma trận là gì?",["Nhiều scalar cộng lại","Nhiều vector cột đặt cạnh nhau","Một vector hàng duy nhất","Một tensor bậc 3"],1,"Ma trận có thể hiểu là nhiều vector cột đặt cạnh nhau. (Mục 3.1)"],
[38,3,"Ma trận thường được ký hiệu bằng:",["Chữ cái viết thường","Chữ cái in hoa (thường in đậm)","Chữ số","Ký hiệu mũi tên"],1,"Ma trận ký hiệu bằng chữ in hoa, thường in đậm. (Mục 3.1)"],
[39,3,"Ký hiệu X ∈ ℝᵐˣⁿ có nghĩa là ma trận có:",["m cột và n hàng","m hàng và n cột","m × n hàng","m + n phần tử"],1,"ℝᵐˣⁿ nghĩa là m hàng, n cột. (Mục 3.1, 3.2)"],
[40,3,"Ma trận X ∈ ℝᵐˣⁿ có tổng cộng bao nhiêu phần tử?",["m + n","m − n","m × n","max(m, n)"],2,"Ma trận m × n có tổng cộng m × n phần tử. (Mục 3.1)"],
[41,3,"“Thần chú” giúp nhớ thứ tự đọc kích thước ma trận là gì?",["“Cột trước, hàng sau”","“Hàng trước, cột sau”","“Lớn trước, nhỏ sau”","“Trái trước, phải sau”"],1,"“Hàng trước, cột sau”. (Mục 3.2)"],
[42,3,"Ma trận B ∈ ℝ⁵ˣ² có bao nhiêu hàng và bao nhiêu cột?",["2 hàng, 5 cột","5 hàng, 2 cột","5 hàng, 5 cột","10 hàng, 1 cột"],1,"ℝ⁵ˣ² = 5 hàng, 2 cột (hàng trước, cột sau). (Mục 3.2)"],
[43,3,"Ma trận B ∈ ℝ⁵ˣ² có tổng cộng bao nhiêu phần tử?",["7","3","10","25"],2,"5 × 2 = 10 phần tử. (Mục 3.2)"],
[44,3,"Phần tử xᵢ,ⱼ của ma trận nằm ở vị trí nào?",["Hàng thứ j, cột thứ i","Hàng thứ i, cột thứ j","Luôn ở góc trên bên trái","Hàng và cột bất kỳ"],1,"xᵢ,ⱼ nằm ở hàng i, cột j (hàng trước, cột sau). (Mục 3.2)"],
[45,3,"Nếu xem ma trận như một bảng dữ liệu, thì một ô bất kỳ trong bảng tương ứng với:",["Scalar","Vector","Matrix","Tensor"],0,"Một ô bất kỳ trong bảng là một scalar. (Mục 3.3)"],
[46,3,"Nếu xem ma trận như một bảng dữ liệu, thì một cột hoặc một hàng tương ứng với:",["Scalar","Vector","Matrix","Tensor"],1,"Một cột hoặc một hàng là một vector. (Mục 3.3)"],
[47,3,"Nếu xem ma trận như một bảng dữ liệu, thì toàn bộ bảng tương ứng với:",["Scalar","Vector","Matrix","Tensor"],2,"Toàn bộ bảng là một matrix. (Mục 3.3)"],
[48,3,"Bảng dữ liệu gồm 100 sample và 8 feature (mỗi hàng một sample, mỗi cột một feature) là ma trận kích thước:",["8 × 100","100 × 8","100 × 100","8 × 8"],1,"100 sample (hàng) × 8 feature (cột) = ma trận 100 × 8. (Mục 3.3)"],
[49,3,"(Đúng/Sai) Ký hiệu ℝ³ˣ⁴ và ℝ⁴ˣ³ mô tả các ma trận có cùng kích thước.",TF,1,"Sai — ℝ³ˣ⁴ (3 hàng, 4 cột) khác ℝ⁴ˣ³; thứ tự quan trọng. (Mục 3.2)"],
[50,3,"Trong ma trận X = [x₁ x₂ ⋯ xₙ], mỗi xⱼ là gì?",["Một scalar","Một vector cột","Một ma trận con","Một hàng của ma trận"],1,"Mỗi xⱼ là một vector cột. (Mục 3.1)"],
[51,4,"Tensor là gì?",["Đối tượng chỉ có hai chiều","Đối tượng tổng quát cho các mảng số nhiều chiều","Một con số duy nhất","Một vector đặc biệt"],1,"Tensor là đối tượng tổng quát cho các mảng số nhiều chiều. (Mục 4.1)"],
[52,4,"Theo cách phân loại theo bậc (order), scalar là tensor bậc mấy?",["Bậc 0","Bậc 1","Bậc 2","Bậc 3"],0,"Scalar là tensor bậc 0. (Mục 4.1)"],
[53,4,"Vector là tensor bậc mấy?",["Bậc 0","Bậc 1","Bậc 2","Bậc 3"],1,"Vector là tensor bậc 1. (Mục 4.1)"],
[54,4,"Matrix là tensor bậc mấy?",["Bậc 0","Bậc 1","Bậc 2","Bậc 3"],2,"Matrix là tensor bậc 2. (Mục 4.1)"],
[55,4,"Lĩnh vực nào thường cần làm việc với tensor có số chiều lớn hơn hai?",["Xử lý văn bản đơn thuần","Thị giác máy tính (computer vision)","Cộng hai số","Giải phương trình bậc nhất"],1,"Thị giác máy tính thường cần tensor nhiều chiều. (Mục 4.1)"],
[56,4,"Một ảnh màu RGB có thể được tách thành mấy ma trận?",["1","2","3 (ứng với Red, Green, Blue)","4"],2,"Ảnh RGB tách thành 3 ma trận: Red, Green, Blue. (Mục 4.2)"],
[57,4,"Một ảnh RGB kích thước 600 × 800 pixel được biểu diễn bằng tensor kích thước:",["600 × 800","600 × 800 × 3","1800 × 800","600 × 800 × 1"],1,"Ảnh 600 × 800 RGB → tensor 600 × 800 × 3. (Mục 4.2)"],
[58,4,"“Thần chú” mô tả tensor là gì?",["Nhiều scalar cộng lại","Nhiều lát ma trận cùng kích thước được xếp chồng (stack) theo chiều sâu","Một vector hàng dài","Một bảng Excel phẳng"],1,"Tensor là nhiều lát ma trận cùng kích thước stack theo chiều sâu. (Mục 4.2)"],
[59,4,"Ba ma trận R, G, B của ảnh màu được xếp chồng theo chiều nào?",["Chiều ngang","Chiều dọc","Chiều sâu (channel)","Không xếp chồng, để rời"],2,"Ba ma trận R, G, B stack theo chiều sâu (channel). (Mục 4.2)"],
[60,4,"(Đúng/Sai) Scalar, vector và matrix đều có thể xem là các trường hợp riêng của tensor, phân loại theo bậc.",TF,0,"Đúng — chúng đều là trường hợp riêng của tensor, phân theo bậc. (Mục 4.1)"],
[61,5,"Operator (toán tử) có thể hiểu là gì?",["Một loại số đặc biệt","Một quy tắc dùng để biến đổi dữ liệu","Một ma trận vuông","Một loại vector"],1,"Operator là một quy tắc dùng để biến đổi dữ liệu. (Đầu Chương 5)"],
[62,5,"Phép cộng hai vector được thực hiện theo kiểu:",["Nhân từng cặp phần tử","Element-wise (cộng từng cặp phần tử ở cùng vị trí)","Cộng dồn tất cả thành một số","Lấy phần tử lớn nhất"],1,"Cộng vector theo kiểu element-wise. (Mục 5.1)"],
[63,5,"Kết quả của [1, 2, 3] + [4, 5, 6] là:",["[5, 7, 9]","[4, 10, 18]","32","[3, 3, 3]"],0,"[1,2,3] + [4,5,6] = [5,7,9]. (Mục 5.1)"],
[64,5,"Kết quả của [4, 5, 6] − [1, 2, 3] là:",["[5, 7, 9]","[3, 3, 3]","[4, 10, 18]","[−3, −3, −3]"],1,"[4,5,6] − [1,2,3] = [3,3,3]. (Mục 5.1)"],
[65,5,"Điều kiện để cộng/trừ hai vector (hoặc hai ma trận) theo kiểu element-wise mặc định là:",["Chúng phải có cùng shape","Chúng phải là ma trận vuông","Một cái phải lớn hơn cái kia","Không có điều kiện nào"],0,"Điều kiện element-wise mặc định: hai toán hạng cùng shape. (Mục 5.1)"],
[66,5,"Phép cộng/trừ vector có làm thay đổi shape của kết quả không?",["Có, luôn tăng số chiều","Không, kết quả giữ nguyên shape với các toán hạng","Có, luôn giảm số chiều","Tùy vào giá trị các phần tử"],1,"Kết quả giữ nguyên shape với các toán hạng. (Mục 5.1)"],
[67,5,"Một vector 3 phần tử có cộng element-wise trực tiếp (không broadcasting) với vector 2 phần tử được không?",["Có, luôn được","Không, vì khác shape","Có, nếu các số đều dương","Có, nếu là vector cột"],1,"Không, vì khác shape (3 vs 2 phần tử). (Mục 5.1)"],
[68,5,"Phép cộng ma trận có tính giao hoán không?",["Có: A + B = B + A","Không bao giờ","Chỉ khi ma trận vuông","Chỉ khi các phần tử dương"],0,"Phép cộng ma trận có tính giao hoán. (Mục 5.2)"],
[69,5,"Phép trừ ma trận có tính giao hoán không?",["Có","Không, trong trường hợp tổng quát A − B ≠ B − A","Luôn luôn có","Chỉ khi ma trận có kích thước lẻ"],1,"Phép trừ nói chung không giao hoán. (Mục 5.2)"],
[70,5,"Hadamard product là phép toán gì?",["Nhân ma trận theo kiểu hàng-nhân-cột","Nhân element-wise (từng cặp phần tử cùng vị trí) giữa hai đối tượng cùng shape","Cộng dồn tất cả phần tử","Phép chuyển vị"],1,"Hadamard product: nhân element-wise giữa hai đối tượng cùng shape. (Mục 5.3)"],
[71,5,"Ký hiệu của Hadamard product là:",["×","⊙","⊘","⊤"],1,"Ký hiệu Hadamard product là ⊙. (Mục 5.3)"],
[72,5,"Kết quả của [1, 2, 3] ⊙ [4, 5, 6] là:",["[5, 7, 9]","[4, 10, 18]","32","[4, 5, 6]"],1,"[1,2,3] ⊙ [4,5,6] = [4,10,18]. (Mục 5.3)"],
[73,5,"Ký hiệu của Hadamard division là:",["⊙","⊘","×","⊤"],1,"Ký hiệu Hadamard division là ⊘. (Mục 5.3)"],
[74,5,"Kết quả của [8, 10, 12] ⊘ [2, 5, 3] là:",["[4, 2, 4]","[4, 5, 4]","[16, 50, 36]","[6, 5, 9]"],0,"[8,10,12] ⊘ [2,5,3] = [4,2,4]. (Mục 5.3)"],
[75,5,"Hadamard product có tính giao hoán không?",["Có: u ⊙ v = v ⊙ u","Không","Chỉ khi hai vector khác nhau","Chỉ với ma trận vuông"],0,"Hadamard product có tính giao hoán. (Mục 5.3)"],
[76,5,"Hadamard division có tính giao hoán không?",["Có","Không","Luôn luôn có","Chỉ khi các phần tử bằng nhau"],1,"Hadamard division không giao hoán. (Mục 5.3)"],
[77,5,"Broadcasting là gì?",["Cơ chế mở rộng tạm thời đối tượng nhỏ hơn cho khớp với đối tượng lớn hơn để thực hiện phép toán element-wise","Phép nhân hai ma trận","Phép chuyển vị ma trận","Cách sắp xếp lại các hàng của ma trận"],0,"Broadcasting: mở rộng tạm thời đối tượng nhỏ hơn cho khớp với đối tượng lớn hơn. (Mục 5.4)"],
[78,5,"(Đúng/Sai) Broadcasting nhất thiết phải tạo ra nhiều bản sao thật của dữ liệu trong bộ nhớ.",TF,1,"Sai — broadcasting là quy tắc tính toán, không nhất thiết tạo bản sao thật. (Mục 5.4)"],
[79,5,"Kết quả của [1, 2, 3] + 10 (broadcasting với scalar) là:",["[11, 12, 13]","[10, 20, 30]","16","[10, 10, 10]"],0,"[1,2,3] + 10 = [11,12,13]. (Mục 5.4)"],
[80,5,"Với ma trận X ∈ ℝ³ˣ², cộng với một vector hàng shape 1 × 2 thì broadcasting diễn ra:",["Theo cột","Theo hàng (lặp lại vector đó xuống từng hàng)","Không thực hiện được","Theo đường chéo"],1,"Vector hàng 1 × 2 broadcast theo hàng (số cột phải khớp). (Mục 5.4)"],
[81,5,"Với ma trận X ∈ ℝ³ˣ², cộng với một vector cột shape 3 × 1 thì broadcasting diễn ra:",["Theo hàng","Theo cột (lặp lại vector đó sang từng cột)","Không thực hiện được","Theo đường chéo"],1,"Vector cột 3 × 1 broadcast theo cột (số hàng phải khớp). (Mục 5.4)"],
[82,5,"Vì sao scalar gần như luôn broadcast được với vector, matrix hay tensor?",["Vì scalar là số lớn nhất","Vì scalar được hiểu là “áp dụng cùng một giá trị cho mọi phần tử”","Vì scalar luôn bằng 0","Vì scalar có nhiều chiều"],1,"Scalar broadcast được vì áp dụng cùng một giá trị cho mọi phần tử. (Mục 5.4)"],
[83,6,"Về bản chất sâu xa nhất, ma trận là gì?",["Một con số phức tạp","Một cách viết cô đọng của cả một hệ phương trình tuyến tính có cùng cấu trúc","Một loại hình ảnh","Một phép chia đặc biệt"],1,"Ma trận là cách viết cô đọng của một hệ phương trình tuyến tính cùng cấu trúc. (Chương 6)"],
[84,6,"Trong bài toán tính điểm trung bình với Toán hệ số 3, Văn hệ số 2, Anh hệ số 1, tổng các hệ số dùng để chia là:",["3","6","1","5"],1,"Tổng hệ số = 3 + 2 + 1 = 6. (Mục 6.1)"],
[85,6,"Khi viết các phương trình tính điểm cho nhiều học sinh, ta nhận ra điều gì về cấu trúc của chúng?",["Mỗi phương trình có cấu trúc hoàn toàn khác nhau","Chúng có cùng cấu trúc, chỉ khác dữ liệu điểm của từng học sinh","Chúng không liên quan gì đến nhau","Chúng đều vô nghiệm"],1,"Các phương trình cùng cấu trúc, chỉ khác dữ liệu từng học sinh. (Mục 6.2)"],
[86,6,"Dạng tổng quát mà đại số tuyến tính dùng để ký hiệu hệ phương trình tuyến tính cô đọng là:",["A + x = b","Ax = b","A ⊙ x = b","Aᵀ = b"],1,"Dạng tổng quát là Ax = b. (Mục 6.3)"],
[87,6,"Trong Ax = b, A là gì?",["Vector kết quả đã biết","Ma trận hệ số (hoặc ma trận dữ liệu), chứa các giá trị đã biết","Vector ẩn cần tìm","Một scalar"],1,"A là ma trận hệ số/dữ liệu, chứa các giá trị đã biết. (Mục 6.3)"],
[88,6,"Trong Ax = b, x là gì?",["Ma trận dữ liệu","Vector ẩn (hoặc vector trọng số) chưa biết cần tìm","Vector kết quả đã biết","Một hằng số"],1,"x là vector ẩn/trọng số chưa biết cần tìm. (Mục 6.3)"],
[89,6,"Trong Ax = b, b là gì?",["Ma trận hệ số","Vector ẩn cần tìm","Vector kết quả đã biết","Một ma trận vuông"],2,"b là vector kết quả đã biết. (Mục 6.3)"],
[90,6,"Trong ví dụ điểm trung bình, mỗi hàng của ma trận điểm số đại diện cho:",["Một môn học (feature)","Một học sinh (sample/individual)","Một hệ số","Điểm trung bình"],1,"Mỗi hàng đại diện cho một học sinh (sample). (Mục 6.1, 6.3)"],
[91,6,"Trong ví dụ điểm trung bình, mỗi cột của ma trận điểm số đại diện cho:",["Một học sinh","Một môn học (feature) — ví dụ toàn bộ điểm Toán","Một hệ số duy nhất","Điểm trung bình"],1,"Mỗi cột đại diện cho một môn học (feature). (Mục 6.1, 6.3)"],
[92,6,"Vì sao vector trọng số phải viết dưới dạng vector cột khi tính Xw?",["Vì cho đẹp","Vì shape phải khớp khi nhân ma trận","Vì vector hàng không tồn tại","Vì trọng số luôn dương"],1,"Vì shape phải khớp khi nhân ma trận. (Mục 6.3, 7.2)"],
[93,6,"Nếu bảng điểm có shape m × n thì vector trọng số cần có shape gì để phép nhân Xw hợp lệ?",["m × 1","n × 1","1 × m","m × n"],1,"Bảng m × n cần vector trọng số shape n × 1. (Mục 6.3, 7.2)"],
[94,6,"Nếu bảng điểm có shape m × n và vector trọng số có shape n × 1, thì kết quả y có shape:",["n × 1","m × 1","m × n","1 × 1"],1,"(m × n) × (n × 1) → (m × 1). (Mục 6.3, 7.2)"],
[95,6,"Câu “Ma trận chỉ là cách viết gọn nhiều phương trình tuyến tính có cùng cấu trúc” nhấn mạnh điều gì?",["Ma trận rất khó hiểu","Bản chất của ma trận là công cụ cô đọng hệ phương trình","Ma trận chỉ dùng trong ảnh","Ma trận là một loại scalar"],1,"Nhấn mạnh bản chất ma trận là công cụ cô đọng hệ phương trình. (Mục 6.3)"],
[96,6,"Theo góc nhìn “tổ hợp tuyến tính của các cột”, tích Ax được tính bằng cách:",["Cộng tất cả phần tử của A và x","Lấy từng cột của A nhân với một số (lấy từ thành phần của x) rồi cộng lại","Nhân từng phần tử cùng vị trí","Chuyển vị A rồi cộng x"],1,"Lấy từng cột của A nhân một số (từ x) rồi cộng lại = tổ hợp tuyến tính. (Mục 6.4)"],
[97,6,"Với A có hai cột [1, 2, 3] và [4, 5, 6], x = [10, 20], tính 10·[1,2,3] + 20·[4,5,6]. Kết quả là:",["[90, 120, 150]","[10, 40, 90]","[30, 30, 30]","[11, 22, 33]"],0,"10[1,2,3] + 20[4,5,6] = [10,20,30] + [80,100,120] = [90,120,150]. (Mục 6.4)"],
[98,6,"Theo góc nhìn tổ hợp tuyến tính, mỗi thành phần của x đóng vai trò như:",["Một chỉ số hàng","Một “liều lượng” pha trộn cho một cột tương ứng của A","Một phần tử cần chuyển vị","Một hằng số cộng thêm"],1,"Mỗi thành phần của x là “liều lượng” pha trộn cho một cột của A. (Mục 6.4)"],
[99,6,"Theo góc nhìn tổ hợp tuyến tính, phương trình Ax = b có nghiệm khi:",["Khi A là ma trận vuông","Khi b có thể tạo ra bằng cách pha trộn (tổ hợp tuyến tính) các cột của A","Khi mọi phần tử của b đều dương","Không bao giờ có nghiệm"],1,"Ax = b có nghiệm khi b tạo được bằng tổ hợp tuyến tính các cột của A. (Mục 6.4)"],
[100,6,"Khi có nhiều bộ trọng số khác nhau, gom chúng lại thì bài toán trở thành:",["Phép cộng ma trận","Phép nhân hai ma trận XW = Y","Phép chuyển vị","Hadamard product"],1,"Gom nhiều bộ trọng số thành ma trận → phép nhân hai ma trận XW = Y. (Mục 6.4, 7.5)"],
[101,6,"(Đúng/Sai) Ax = b chỉ là một cách viết gọn, về bản chất tương đương với cả một hệ nhiều phương trình tuyến tính.",TF,0,"Đúng — Ax = b tương đương với cả một hệ phương trình, chỉ viết gọn hơn. (Mục 6.3)"],
[102,6,"Các khái niệm nâng cao nào được nhắc là “bắt rễ” từ biểu thức Ax = b?",["Không gian cột, hạng của ma trận, độc lập tuyến tính","Đạo hàm và tích phân","Số phức và lượng giác","Hình học không gian"],0,"Không gian cột, hạng (rank), độc lập tuyến tính. (Mục 6.4)"],
[103,7,"Cho A ∈ ℝᵐˣⁿ và x ∈ ℝⁿ. Tích Ax là một vector thuộc:",["ℝⁿ","ℝᵐ","ℝᵐˣⁿ","ℝ"],1,"Ax là vector thuộc ℝᵐ. (Mục 7.1)"],
[104,7,"Mỗi thành phần bᵢ của tích Ax được tính bằng cách:",["Cộng tất cả phần tử của hàng i","Lấy hàng thứ i của A nhân tương ứng với vector x rồi cộng lại (dot product)","Nhân phần tử aᵢᵢ với xᵢ","Lấy phần tử lớn nhất của hàng i"],1,"Mỗi bᵢ = dot product của hàng thứ i với vector x. (Mục 7.1)"],
[105,7,"Công thức tổng quát cho bᵢ là:",["bᵢ = Σⱼ₌₁ⁿ aᵢⱼxⱼ","bᵢ = aᵢᵢ + xᵢ","bᵢ = maxⱼ aᵢⱼ","bᵢ = aᵢ₁ × x₁ (chỉ phần tử đầu)"],0,"bᵢ = Σⱼ₌₁ⁿ aᵢⱼxⱼ. (Mục 7.1)"],
[106,7,"Có thể diễn đạt: phép nhân ma trận với vector chính là:",["Một phép cộng đơn giản","Nhiều dot product song song, mỗi dot product ứng với một hàng","Một phép chuyển vị","Nhân từng cặp phần tử cùng vị trí"],1,"Là nhiều dot product song song, mỗi cái ứng với một hàng. (Mục 7.1)"],
[107,7,"Điều kiện để phép nhân Ax hợp lệ là:",["Số hàng của A bằng số cột của x","Số cột của A bằng số phần tử (số hàng) của x","A và x phải cùng shape","A phải là ma trận vuông"],1,"Số cột của A phải bằng số phần tử (số hàng) của x. (Mục 7.2)"],
[108,7,"“Thần chú” nào giúp nhớ quy tắc shape khi nhân?",["“Hàng trước, cột sau”","“Đuôi thằng này phải bằng đầu thằng kia”","“Vector cột = 1 feature”","“Lớn nhân nhỏ”"],1,"“Đuôi thằng này phải bằng đầu thằng kia”. (Mục 7.2)"],
[109,7,"Trong tích A(m × n) · x(n × 1), hai con số nào phải bằng nhau?",["m và 1","m và n","Con số n ở đuôi của A và con số n ở đầu của x","Không cần bằng nhau"],2,"Con số n ở đuôi của A phải bằng n ở đầu của x. (Mục 7.2)"],
[110,7,"Kết quả của phép nhân (m × n) × (n × 1) có shape:",["(n × 1)","(m × 1)","(m × n)","(n × n)"],1,"(m × n) × (n × 1) → (m × 1). (Mục 7.2)"],
[111,7,"Cho A = [[1, 2], [3, 4]] và x = [1, 2]. Giá trị b₁ (hàng 1) là:",["1×1 + 2×2 = 5","1×1 + 3×2 = 7","1 + 2 = 3","1 × 2 = 2"],0,"b₁ = 1×1 + 2×2 = 5. (Mục 7.3)"],
[112,7,"Với cùng dữ liệu câu trên, giá trị b₂ (hàng 2) là:",["3×1 + 4×2 = 11","3 + 4 = 7","2×1 + 4×2 = 10","3 × 2 = 6"],0,"b₂ = 3×1 + 4×2 = 11. (Mục 7.3)"],
[113,7,"Vậy kết quả Ax của hai câu trên là:",["[5, 11]","[7, 7]","[1, 8]","[3, 6]"],0,"Ax = [5, 11]ᵀ. (Mục 7.3)"],
[114,7,"Điểm khác biệt cốt lõi giữa phép nhân ma trận và Hadamard product là gì?",["Không có khác biệt","Nhân ma trận có bước cộng dồn (dot product theo hàng); Hadamard chỉ nhân từng cặp phần tử cùng vị trí","Hadamard cần ma trận vuông, nhân ma trận thì không","Nhân ma trận chỉ dùng cho scalar"],1,"Nhân ma trận có bước cộng dồn; Hadamard chỉ nhân từng cặp phần tử. (Mục 7.4)"],
[115,7,"Cho A = [[1, 2], [3, 4]], B = [[5, 6], [7, 8]]. Tích Hadamard A ⊙ B là:",["[[19, 22], [43, 50]]","[[5, 12], [21, 32]]","[[6, 8], [10, 12]]","[[5, 6], [7, 8]]"],1,"A ⊙ B: nhân từng cặp → [[5, 12], [21, 32]]. (Mục 7.4)"],
[116,7,"Với cùng A, B ở câu trên, tích ma trận AB cho phần tử ở góc trên trái là:",["1 × 5 = 5","1×5 + 2×7 = 19","1×5 + 2×6 = 17","1 + 5 = 6"],1,"AB góc trên trái = 1×5 + 2×7 = 19. (Mục 7.4)"],
[117,7,"(Đúng/Sai) Phép nhân ma trận và Hadamard product thường cho cùng một kết quả nếu áp dụng lên cùng cặp ma trận.",TF,1,"Sai — hai phép thường cho kết quả khác hẳn nhau. (Mục 7.4)"],
[118,7,"Phép nhân ma trận nói chung có tính giao hoán không?",["Có, luôn luôn","Không, nói chung AB ≠ BA","Chỉ khi các phần tử dương","Chỉ khi là vector"],1,"Phép nhân ma trận nói chung không giao hoán. (Mục 7.4)"],
[119,7,"Nếu A có shape (3, 2) và x có shape (3, 1), phép nhân Ax có hợp lệ không?",["Có, vì cùng có số 3","Không, vì số cột của A là 2 nhưng số hàng của x là 3 (không khớp)","Có, luôn hợp lệ","Chỉ khi chuyển vị x"],1,"Không hợp lệ: số cột của A (2) khác số hàng của x (3). (Mục 7.2)"],
[120,7,"Để phép nhân Ax (với A shape (3, 2)) hợp lệ, x cần có shape:",["(3, 1)","(2, 1)","(1, 3)","(3, 3)"],1,"Với A shape (3, 2), x cần shape (2, 1). (Mục 7.2)"],
];

export const QUESTIONS = raw.map(([id, ch, q, opts, ans, exp]) => ({ id, ch, q, opts, ans, exp }));
